[workspace]
members = [
    ".",
    "ezlz_macros",
]
resolver = "2"

[dev-dependencies]
criterion = "0.7"
mimalloc = "0.1.52"

[[bench]]
name = "benchmarks"
harness = false

[package]
name = "ezlz"
version = "1.2.6"
edition = "2024"
description = "A compact i18n crate optimized for hot loops."
license = "MIT"
repository = "https://github.com/shmeowker/ezlz"
readme = "README.md"
keywords = ["i18n", "l10n", "pluralization", "localization"]
categories = ["localization", "internationalization"]

[package.metadata.docs.rs]
rustdoc-args = ["--document-private-items"]

[dependencies]
ahash = "0.8.12"
ezlz-macros = { path = "ezlz_macros", version = "0.2.2" }
itoa = "1.0.18"
serde_yaml = "0.9"
zmij = { version = "1.0.23" }

[features]
default = []
missing-key-nopanic = []
